raw_csv: "data/raw/test-task/clusters.csv"
cleaned_csv: "data/processed/clusters_cleaned.csv"
raw_images: "data/raw/test-task/clusters/"
cleaned_images: "data/processed/cleaned_clusters/"
width_to_remove: 1920
height_to_remove: 1080
